//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://schemas.datacontract.org/2004/07/Monitor")]
    [System.SerializableAttribute()]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> INField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> IaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> IbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> IcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> IgfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Address {
            get {
                return this.AddressField;
            }
            set {
                if ((this.AddressField.Equals(value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> IN {
            get {
                return this.INField;
            }
            set {
                if ((this.INField.Equals(value) != true)) {
                    this.INField = value;
                    this.RaisePropertyChanged("IN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Ia {
            get {
                return this.IaField;
            }
            set {
                if ((this.IaField.Equals(value) != true)) {
                    this.IaField = value;
                    this.RaisePropertyChanged("Ia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Ib {
            get {
                return this.IbField;
            }
            set {
                if ((this.IbField.Equals(value) != true)) {
                    this.IbField = value;
                    this.RaisePropertyChanged("Ib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Ic {
            get {
                return this.IcField;
            }
            set {
                if ((this.IcField.Equals(value) != true)) {
                    this.IcField = value;
                    this.RaisePropertyChanged("Ic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Igf {
            get {
                return this.IgfField;
            }
            set {
                if ((this.IgfField.Equals(value) != true)) {
                    this.IgfField = value;
                    this.RaisePropertyChanged("Igf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEDSService")]
    public interface IEDSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/UpdateDevice", ReplyAction="http://tempuri.org/IEDSService/UpdateDeviceResponse")]
        byte[] UpdateDevice(byte zid, byte address, int zoneIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/UpdateDevice", ReplyAction="http://tempuri.org/IEDSService/UpdateDeviceResponse")]
        System.Threading.Tasks.Task<byte[]> UpdateDeviceAsync(byte zid, byte address, int zoneIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/RemoteControl", ReplyAction="http://tempuri.org/IEDSService/RemoteControlResponse")]
        byte[] RemoteControl(byte zid, byte[] snd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/RemoteControl", ReplyAction="http://tempuri.org/IEDSService/RemoteControlResponse")]
        System.Threading.Tasks.Task<byte[]> RemoteControlAsync(byte zid, byte[] snd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/QueryData", ReplyAction="http://tempuri.org/IEDSService/QueryDataResponse")]
        Monitor.ServiceReference1.Record[] QueryData(byte zid, byte address, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/QueryData", ReplyAction="http://tempuri.org/IEDSService/QueryDataResponse")]
        System.Threading.Tasks.Task<Monitor.ServiceReference1.Record[]> QueryDataAsync(byte zid, byte address, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/QueryTrip", ReplyAction="http://tempuri.org/IEDSService/QueryTripResponse")]
        EDSLot.Trip[] QueryTrip(byte zid, byte address, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/QueryTrip", ReplyAction="http://tempuri.org/IEDSService/QueryTripResponse")]
        System.Threading.Tasks.Task<EDSLot.Trip[]> QueryTripAsync(byte zid, byte address, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/ChangeDeviceLiveness", ReplyAction="http://tempuri.org/IEDSService/ChangeDeviceLivenessResponse")]
        void ChangeDeviceLiveness(byte zid, byte address, int liveness);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/ChangeDeviceLiveness", ReplyAction="http://tempuri.org/IEDSService/ChangeDeviceLivenessResponse")]
        System.Threading.Tasks.Task ChangeDeviceLivenessAsync(byte zid, byte address, int liveness);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/QueryEnergy", ReplyAction="http://tempuri.org/IEDSService/QueryEnergyResponse")]
        EDSLot.Energy[] QueryEnergy(int[] addrs, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/QueryEnergy", ReplyAction="http://tempuri.org/IEDSService/QueryEnergyResponse")]
        System.Threading.Tasks.Task<EDSLot.Energy[]> QueryEnergyAsync(int[] addrs, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/GetUpsState", ReplyAction="http://tempuri.org/IEDSService/GetUpsStateResponse")]
        string GetUpsState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/GetUpsState", ReplyAction="http://tempuri.org/IEDSService/GetUpsStateResponse")]
        System.Threading.Tasks.Task<string> GetUpsStateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEDSServiceChannel : Monitor.ServiceReference1.IEDSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDSServiceClient : System.ServiceModel.ClientBase<Monitor.ServiceReference1.IEDSService>, Monitor.ServiceReference1.IEDSService {
        
        public EDSServiceClient() {
        }
        
        public EDSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] UpdateDevice(byte zid, byte address, int zoneIndex) {
            return base.Channel.UpdateDevice(zid, address, zoneIndex);
        }
        
        public System.Threading.Tasks.Task<byte[]> UpdateDeviceAsync(byte zid, byte address, int zoneIndex) {
            return base.Channel.UpdateDeviceAsync(zid, address, zoneIndex);
        }
        
        public byte[] RemoteControl(byte zid, byte[] snd) {
            return base.Channel.RemoteControl(zid, snd);
        }
        
        public System.Threading.Tasks.Task<byte[]> RemoteControlAsync(byte zid, byte[] snd) {
            return base.Channel.RemoteControlAsync(zid, snd);
        }
        
        public Monitor.ServiceReference1.Record[] QueryData(byte zid, byte address, System.DateTime start, System.DateTime end) {
            return base.Channel.QueryData(zid, address, start, end);
        }
        
        public System.Threading.Tasks.Task<Monitor.ServiceReference1.Record[]> QueryDataAsync(byte zid, byte address, System.DateTime start, System.DateTime end) {
            return base.Channel.QueryDataAsync(zid, address, start, end);
        }
        
        public EDSLot.Trip[] QueryTrip(byte zid, byte address, System.DateTime start, System.DateTime end) {
            return base.Channel.QueryTrip(zid, address, start, end);
        }
        
        public System.Threading.Tasks.Task<EDSLot.Trip[]> QueryTripAsync(byte zid, byte address, System.DateTime start, System.DateTime end) {
            return base.Channel.QueryTripAsync(zid, address, start, end);
        }
        
        public void ChangeDeviceLiveness(byte zid, byte address, int liveness) {
            base.Channel.ChangeDeviceLiveness(zid, address, liveness);
        }
        
        public System.Threading.Tasks.Task ChangeDeviceLivenessAsync(byte zid, byte address, int liveness) {
            return base.Channel.ChangeDeviceLivenessAsync(zid, address, liveness);
        }
        
        public EDSLot.Energy[] QueryEnergy(int[] addrs, System.DateTime start, System.DateTime end) {
            return base.Channel.QueryEnergy(addrs, start, end);
        }
        
        public System.Threading.Tasks.Task<EDSLot.Energy[]> QueryEnergyAsync(int[] addrs, System.DateTime start, System.DateTime end) {
            return base.Channel.QueryEnergyAsync(addrs, start, end);
        }
        
        public string GetUpsState() {
            return base.Channel.GetUpsState();
        }
        
        public System.Threading.Tasks.Task<string> GetUpsStateAsync() {
            return base.Channel.GetUpsStateAsync();
        }
    }
}
