//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEDSService")]
    public interface IEDSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/UpdateDevice", ReplyAction="http://tempuri.org/IEDSService/UpdateDeviceResponse")]
        byte[] UpdateDevice(byte address, int zoneIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEDSService/UpdateDevice", ReplyAction="http://tempuri.org/IEDSService/UpdateDeviceResponse")]
        System.Threading.Tasks.Task<byte[]> UpdateDeviceAsync(byte address, int zoneIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEDSServiceChannel : Monitor.ServiceReference1.IEDSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDSServiceClient : System.ServiceModel.ClientBase<Monitor.ServiceReference1.IEDSService>, Monitor.ServiceReference1.IEDSService {
        
        public EDSServiceClient() {
        }
        
        public EDSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] UpdateDevice(byte address, int zoneIndex) {
            return base.Channel.UpdateDevice(address, zoneIndex);
        }
        
        public System.Threading.Tasks.Task<byte[]> UpdateDeviceAsync(byte address, int zoneIndex) {
            return base.Channel.UpdateDeviceAsync(address, zoneIndex);
        }
    }
}
