//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeEDSLot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_Measure
    {
        public System.DateTime Time { get; set; }
        public Nullable<int> ZID { get; set; }
        public int Address { get; set; }
        public Nullable<double> U { get; set; }
        public Nullable<double> I { get; set; }
        public Nullable<double> F { get; set; }
        public Nullable<double> PF { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> Q { get; set; }
        public Nullable<double> PE { get; set; }
        public Nullable<double> QE { get; set; }
    }
}
