//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeEDSLot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public System.DateTime Time { get; set; }
        public int ZID { get; set; }
        public int Address { get; set; }
        public string Phase { get; set; }
        public string Type { get; set; }
        public Nullable<double> Ia { get; set; }
        public Nullable<double> Ib { get; set; }
        public Nullable<double> Ic { get; set; }
        public Nullable<double> IN { get; set; }
        public Nullable<double> It { get; set; }
        public Nullable<double> Tt { get; set; }
        public Nullable<double> Ip { get; set; }
        public Nullable<double> Tp { get; set; }
        public Nullable<double> Ir { get; set; }
        public Nullable<double> Ig { get; set; }
    }
}
